name: FrontCI

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  userCItest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm test

  publish-npm:
    needs: userCItest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
         
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build
      
      
    ## 웹 이미지 빌드 및 도커허브에 push
    #- name: web docker build and push
    # run: |
    #  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #    docker build -t ${{ secrets.DOCKER_REPO }}/ci-test ./
    #    docker push ${{ secrets.DOCKER_REPO }}/ci-test
    #- name: Get timestamp
    #  uses: gerred/actions/current-time@master
    #  id: current-time

    #- name: Run string replace
    #  uses: frabert/replace-string-action@master
    #  id: format-time
    #  with:
    #    pattern: '[:\.]+'
    #    string: "${{ steps.current-time.outputs.time }}"
    #    replace-with: '-'
    #    flags: 'g'

    #- name: Beanstalk Deploy
    #  uses: einaregilsson/beanstalk-deploy@v20
    #  with:
    #    aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    application_name: cicd
    #    environment_name: Cicd-env
    #    version_label: "github-action--${{ steps.format-time.outputs.replaced }}"
    #    region: ap-northeast-2
    #    deployment_package: Dockerrun.aws.json





     
